apiVersion: apps/v1
kind: Deployment
metadata:
  name: receipt
  labels:
    app: receipt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receipt
  template:
    metadata:
      labels:
        app: receipt
    spec:
      containers:
      - name: receipt
        image: kster/receipt:1.0
        ports:
        - containerPort: 9001
        env:
        - name: STORE_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: store-s3
              key: store-access-key
        - name: STORE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: store-s3
              key: store-secret-key
        - name: DB_URL    
          valueFrom:
            configMapKeyRef:
              name: mariadb
              key: database-url
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mariadb
              key: database-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: database-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: database-password
---
apiVersion: v1
kind: Service
metadata:
  name: receipt
  labels:
    app: receipt
spec:
  ports:
  - port: 9001
    protocol: TCP
  selector:
    app: receipt
  type: NodePort        
